
import pandas as pd
import sys
import numpy as np
#import preprocess
from datetime import datetime, timedelta

#path = 'F:/20181110_gpsHealth/data/aws_sync/6_cities_201807_201811/'
#processpath = 'F:/20181110_gpsHealth/process/v3/'
# path = '/media/wwang/easystore/20181110_gpsHealth/data/aws_sync/6_cities_201807_201811/'
# processpath = '/media/wwang/easystore/20181110_gpsHealth/process/v3/'
path = 'F:/20181110_gpsHealth/data/aws_sync/6_cities_201807_201811/'
processpath = 'F:/20181110_gpsHealth/process/v3/'
import pytz
mytz = pytz.timezone('America/New_York')


cities = ['wilmington','chattanooga','charleston','savanna','knoxville','newport_news']
cities_placeID = ['wilmington','savanna','newport_news']



temp = pd.read_excel(processpath+'iddict_v1.xlsx')  # datedict_v1.xlsx and iddict_v1.xlsx are both generated by id_date_convert_v1.py
iddict = dict(zip(temp['advertiser_id'],temp['advertiser_id_convertedid']))
del temp

cities = ['wilmington','chattanooga','charleston','savanna','knoxville','newport_news']
for city in cities:
    print('working on: ',city)
    file = '%s_07_11_both_valid10'%city    
    family = pd.read_pickle(processpath+'%s_family.pickle'%file)
    
    fam_uidslist = family['advertiser_id'].tolist()
    
    
    familySizes = []
    userids = []
    newids = []
    for i,fam_uids in enumerate(fam_uidslist):
        if len(fam_uids) > 1:
            for fam_uid in fam_uids:
                userids.append(fam_uid)
                familySizes.append(len(fam_uids))
                try:
                    newids.append(iddict[fam_uid])
                except:
                    newids.append(9999999)  #9999999 indicates unknown users whose family size should be 0
                    
        else:
            userids.append(fam_uids[0])
            familySizes.append(1)
            try:
                newids.append(iddict[fam_uid])
            except:
                newids.append(9999999)  #9999999 indicates unknown users whose family size should be 0
    
    
    data = pd.DataFrame()
    data['advertiser_id'] = userids
    data['advertiser_id_convertedid'] = newids
    data['familySize'] = familySizes
    print('')
    print('saving')
    data.to_csv(processpath+'%s_07_11_both_valid10_familySize.csv'%city,index=False)
    del data
