
import pandas as pd
import sys
import numpy as np
import preprocess

#path = 'F:/20181110_gpsHealth/data/aws_sync/6_cities_201807_201811/'
#processpath = 'F:/20181110_gpsHealth/process/v3/'
# path = '/media/wwang/easystore/20181110_gpsHealth/data/aws_sync/6_cities_201807_201811/'
# processpath = '/media/wwang/easystore/20181110_gpsHealth/process/v3/'
path = 'F:/20181110_gpsHealth/data/aws_sync/6_cities_201807_201811/'
processpath = 'F:/20181110_gpsHealth/process/v3/'




#cities = ['wilmington','chattanooga','charleston','savanna','knoxville','newport_news']
cities = ['wilmington','chattanooga','charleston','savanna','knoxville','newport_news']
for city in cities:
    print('working on: ',city)
    
    temp = pd.read_csv(processpath+'%s_07_11_both_valid10_familySize.csv'%city) # s_07_11_both_valid10_familySize.csv was generated by calFamilySize.py
    sizedict = dict(zip(temp['advertiser_id_convertedid'],temp['familySize']))
    usersWithFamilys = temp['advertiser_id_convertedid'].tolist()
    del temp
    
    
    data = pd.read_csv(processpath+'%s_07_11_both_valid10_abouthome_placeID_simpleid.csv'%city)
    
    userids = data['advertiser_id'].to_list()
    familySizes = []
    for userid in userids:
        if userid in usersWithFamilys:
            familySizes.append(sizedict[userid])
        else:
            familySizes.append(0)
    
    data['familySize']=familySizes
    data = data.loc[data['familySize']>1]
    print('')
    print('saving')
    #data = outdf
    data.to_csv(processpath+'%s_07_11_both_valid10_abouthome_placeID_simpleid_familySize.csv'%city,index=False)
    del data

